---
services:
  node:
    build:
      dockerfile: Dockerfile
      context: .docker/node
    ports:
      - 3030:3000
    volumes:
      - ./:/var/www/html
  postgres:
    build:
      dockerfile: Dockerfile
      context: .docker/postgres
    ports:
      - 54330:5432
    volumes:
      - postgres:/var/lib/postgres/data
    environment:
      POSTGRES_USER: apple
      POSTGRES_PASSWORD: apple
      POSTGRES_DB: apple

volumes:
  postgres: