apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weather-auth-database-pvc
  namespace: weather-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
