apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: weather-app
spec:
  selector:
    app: weather-app-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432 
  type: NodePort
